### PR TITLE
Solving Issue #11

### PR DESCRIPTION
**Pull request by eddiechoi00**
## Patch Notes
Addressing Issue #11; if the user uses @wustl.edu, the option for live or online will appear.
If the user does not use a @wustl.edu email, then a confirmation checkbox will appear acknowledging that non-WashU students will only be able to attend the event online.

## Additional Notes (optional)
I may have made some unnecessary changes to make this work, please call me out if I did.
Also had trouble getting the live or online options horizontally instead of vertically; looks like all the other sections are grouped under a ```<style>``` head, but couldn't really figure out a way to fit the new ID I created into that.
It's a very minor thing just for the aesthetics, but if it's an easy fix, I think it'll be worth it.

Screen Shot 2022-07-03 at 5 02 21 PM
Screen Shot 2022-07-03 at 5 02 31 PM

### CODE REVIEW

**Comment by jackheuberger** [comment]
I don't have time to review tonight but will take a look tomorrow. Did you by any chance see user/model.py? What I did when I took a crack at this one was adding a new function to the user class called is_wustl that returned true if the email contained @wustl.edu or not

**Comment by eddiechoi00** [comment]
That's kinda what I did, the unnecessary changes I was talking about was to call the current user's email from views.py.

The css part I was talking about is pretty much neglectable if you don't mind how it looks.

**Comment by jackheuberger** [comment]
I was able to get the is_wustl field updating properly on [user creation](https://github.com/Hack-WashU/myhackwashu/commit/ac4d8c8f7a5d755984006fd0c65f5ae12a6fc81f#diff-51b25f3ad8782ea0528597413f4ebed24af85507c013c1637a00db97e745817f). Are you able to make changes to the `user_wustl` branch in this repo? I don't think it should be protected.

How were you able to pass the is_wustl data to the form?

**Comment by eddiechoi00** [comment]
I wasn't aware about the is_wustl field before, so I ended up making a request for the user on views.py and feeding it into forms.py as a parameter on the classes.
We can't make a request on forms.py so I had to do it through views.py.

I can't check right now if I can make changes to the `user_wustl` branch but I will when I get the chance.

**Review by jackheuberger — CHANGES_REQUESTED** [review]
I checked out your branch, pulled new changes from origin/main, and ran the app. I created an admin account using a wustl email by putting it in the list of `HACKATHON_ORGANIZER_EMAILS` in `app/hackathon_variables.py`. Then I created an account using a non-wustl email and went to submit an application.

When I click the submit button, I get an error:
image

**Comment by jackheuberger** [comment]
Maybe it has something to do with two different forms existing? It's an error with the form being valid, maybe an error with the live/online question not being included in the form for non-wustl people?

**Pull request merged**
